---
- hosts: ceph00-ansible
  remote_user: root
  become: no
  gather_facts: false
  become_method: sudo
  tasks:
    - name: "Cluster /etc/ansible/hosts file"
      copy:
        src: "files/main_ansible_hosts"
        dest: /etc/ansible/hosts
        owner: root
        group: root
        mode: u=rw,g=r,o=r
